server:
  port: 8080

spring:
  application:
    name: employee-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-sandeep-secure.us.auth0.com/
          audience: https://sandeep-secure-resource-endpoint/

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents,retryevents,metrics,retires

  endpoint:
    health:
      show-details: always

resilience4j:

  circuitbreaker:
    instances:
      employeeServiceCB:

        failureRateThreshold: 50
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

        recordExceptions:
          - java.lang.Exception
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException

        ignoreExceptions:
          - java.lang.IllegalArgumentException
  retry:
    instances:
      employeeRetry:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.lang.RuntimeException
          - org.springframework.web.client.ResourceAccessException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  timelimiter:
    instances:
      employeeServiceCB:
        timeoutDuration: 3s